services:
  rabbitmq:
    image: rabbitmq:3.8.16-management-alpine
    container_name: rabbitmq-sandbox
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
